---
- name: Create letsencrypt certificate
  tags: create_le_cert
  become: true
  ansible.builtin.shell: |
    letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
#    letsencrypt certonly --test-cert -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}
  notify:
    - nginx reload
- name: Install nginx site for specified site
  tags: site_cfg
  become: true
  ansible.builtin.template:
    src: nginx-le.j2
    dest: /etc/nginx/sites-enabled/le_{{ domain_name }}.conf
    mode: '0640'
  notify:
    - nginx reload
# Check new nginx config by reload one before write change in cron
- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers
- name: Add letsencrypt cronjob for cert renewal
  tags: cron_update
  become: true
  ansible.builtin.cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }} && service nginx reload
  notify:
    - cron restart
# _EOF_
