- name: 'Install nginx & letsencrypt & DH-group'
#  tags: [install_pkgs, never]
  become: true
  block:
    - name: 'Install mariadb'
      ansible.builtin.apt:
        pkg: [mariadb, mariadb-server]
        update_cache: true
        cache_valid_time: '28800'
        update_cache: yes
    - name: start and enable mysql service
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes
- name: creating mysql user (medium_post)
  community.mysql.mysql_user:
    name: "{{db_user}}"
    password: "{{db_pass}}"
    priv: '*.*:ALL'
    host: '%'
    state: present
- name: creating database
  community.mysql.mysql_db:
    name: "{{db_name}}"
    state: present
- name: Enable remote login to mysql
  ansible.builtin.lineinfile:
     path: /etc/mysql/mysql.conf.d/mysqld.cnf
     regexp: '^bind-address'
     line: 'bind-address = 0.0.0.0'
     backup: yes
  notify:
     - mysql restart
# _EOF_
