---
# MySQL install & enable replication.
# First run cmd: ansible-playbook -i inventory/stage/hosts.yml sql.yml -vv --tags never,config
- hosts: db01,db02
  vars:
    master_db_srv_name: 'db01'
    slave_db_srv_name: 'db02'
    wp_db: 'wordpress'
    wp_user: 'wordpress'
    wp_user_pw: 'wordpress'
  become: true
  gather_facts: false
  roles:
    - mysql_repl
# _EOF_
