---
# file: dbservers.yml
# Playbook for instance [db01, db02]
- hosts: dbservers
  gather_facts: false
  become_method:
    sudo
  become_user:
    root
  remote_user:
    yc-user
  tasks:
    - name: 'Install Mysql (mariadb) with database and remote login'
      import_role:
        name: mariadb_install 
      vars:
        db_user: wordpress
        db_name: wordpress
        db_pass: wordpress
# _EOF_
