---
# file: dbservers.yml
# Playbook for instance [db01, db02]
- hosts: db01
  gather_facts: false
  become: true
  become_method: sudo
#  become_user: root
  remote_user: yc-user
  tasks:
    - name: 'install mysql-mariadb & create database & remote login'
      import_role:
        name: mariadb_install
      vars:
        db_user: wordpress
        db_name: wordpress
        db_pass: wordpress
        mysql_root_password: testpas714!forot
# _EOF_
