---
# file: nat-instance.yml
# Install & config Nginx reverse proxy on "nat-instance"
- hosts: nat-instance
  gather_facts: false
  vars:
    nginx_user: 'www-data'
    letsencrypt_email: 'ok.digit@ya.ru'
    rev_proxy_external_ip_address: '51.250.65.167'
    rev_proxy_allow_ip_address: '212.176.228.226'
  remote_user:
    yc-user
  tasks:
# WWW - default site config
    - name: 'Install nginx, letsencrypt. Generate DH-group. Create default site config'
      ansible.builtin.import_role:
        name: proxy_le_www
      vars:
        domain_name: 'www.gw22.pw'
        rev_proxy_socket: '10.20.0.100:443'
# Additional sites:
# Gitlab
    - name: 'Import nginx_le_add_site role for gitlab.gw22.pw'
      ansible.builtin.import_role:
        name: proxy_le_add_site
      tags: [create_le_cert, site_cfg]
      vars:
        domain_name: 'gitlab.gw22.pw'
        rev_proxy_socket: '10.30.0.50:80'
# Grafana
    - name: 'Import nginx_le_add_site role for grafana.gw22.pw'
      ansible.builtin.import_role:
        name: proxy_le_add_site
      tags: [create_le_cert, site_cfg]
      vars:
        domain_name: 'grafana.gw22.pw'
        rev_proxy_socket: '10.30.0.200:3000'
# Prometheus
    - name: 'Import nginx_le_add_site role for prometeus.gw22.pw'
      ansible.builtin.import_role:
        name: proxy_le_add_site
      tags: [create_le_cert, site_cfg]
      vars:
        domain_name: 'prometeus.gw22.pw'
        rev_proxy_socket: '10.30.0.200:9090'
# Aletmanager
    - name: 'Import nginx_le_add_site role for alertmanager.gw22.pw'
      ansible.builtin.import_role:
        name: proxy_le_add_site
      tags: [create_le_cert, site_cfg]
      vars:
        domain_name: 'alertmanager.gw22.pw'
        rev_proxy_socket: '10.30.0.200:9093'
# _EOF_
