---
# file: nat-instance.yml
# Playbook for instance "nat-instance"
- hosts: nat-instance
  gather_facts: false
  vars:
    nginx_user: 'www-data'
    letsencrypt_email: 'ok.digit@ya.ru'
  become_method:
    sudo
  become_user:
    root
  remote_user:
    yc-user
  tasks:
    - name: 'Install nginx, letsencrypt. Generate DH-group. Create default site config'
      import_role:
        name: nginx_le_install
      vars:
        domain_name: 'www.gw22.pw'
        external_ip_address: '51.250.65.167'
        rev_proxy_socket: '10.20.0.100:443'
    - name: 'Import nginx_le_add_site role for gitlab.gw22.pw'
      import_role:
        name: nginx_le_add_site
      tags: [create_le_cert, site_cfg]
      vars:
        domain_name: 'gitlab.gw22.pw'
        rev_proxy_socket: '10.30.0.50:443'
    - name: 'Import nginx_le_add_site role for grafana.gw22.pw'
      import_role:
        name: nginx_le_add_site
      tags: [create_le_cert, site_cfg]
      vars:
        domain_name: 'grafana.gw22.pw'
        rev_proxy_socket: '10.30.0.200:3000'
    - name: 'Import nginx_le_add_site role for prometeus.gw22.pw'
      import_role:
        name: nginx_le_add_site
      tags: [create_le_cert, site_cfg]
      vars:
        domain_name: 'prometeus.gw22.pw'
        rev_proxy_socket: '10.30.0.200:9090'
    - name: 'Import nginx_le_add_site role for alertmanager.gw22.pw'
      import_role:
        name: nginx_le_add_site
      tags: [create_le_cert, site_cfg]
      vars:
        domain_name: 'alertmanager.gw22.pw'
        rev_proxy_socket: '10.30.0.200:9093'
# _EOF_

