---
# file: inventories/stage/hosts.yml
all:

  hosts:
    bastion:
      ansible_host: 51.250.75.189
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  children:
    apps:
      children:

        rproxy:
          hosts:
            nat-instance:
              ansible_host: 10.0.0.5
              virtual_domain: gw22.pw
        dbservers:
          hosts:
            db01:
              ansible_host: 10.20.0.150
            db02:
              ansible_host: 10.120.0.150

        webapp:
          hosts:
            app:
              ansible_host: 10.20.0.100

    tools:
      children:

        cicd:
          hosts:
            gitlab:
              ansible_host: 10.30.0.50
            runner:
              ansible_host: 10.30.0.51

        mon:
          hosts:
            monitoring:
              ansible_host: 10.30.0.200
