---
# file: roles/nginx/handlers/main.yml

# NGINX - enable service by systemd
- name: nginx systemd
  become: true
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started

# NGINX - restart service
- name: nginx restart
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted

# NGINX - reload nginx to activate specified site
- name: nginx reload
  become: true
  ansible.builtin.service:
    name: nginx
    state: reloaded

# CRON - Restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes
# - name: cron restart reload
- name: cron restart
  become: true
  ansible.builtin.service:
#    state: restarted
#    daemon_reload: yes
    name: cron
    state: restarted
