# file: roles/php/tasks/main.yml
- name: 'Renew repo for PHP'
  block:
    - name: 'Add ondrej-php repository from PPA'
      become: true
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php
    - name: 'Only run "update_cache=yes" if the last one is more than 28800 seconds ago'
      become: true
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 28800
- name: 'Install php'
  become: true
  apt: pkg={{ item }}
  with_items:
    - php
    - php-common
    - php-cli
    - php-fpm
    - php-curl
    - php-mysql
    - php-readline
    - php-mbstring
    - php-xml
    - php-intl
#    - php-opcache
    - php-gd
    - libapache2-mod-php
  notify: restart php-fpm
# _EOF_
